//
//  GamesGlobalVariables.swift
//  Writing Games
//
//  Created by Hannah Dadd on 16/01/2026.
//

import Foundation
import SwiftUI

struct GamesGlobalVariables {
    
    static var tones = [
        "formal",
        "sarcastic",
        "aggressive",
        "empathetic",
        "reluctant",
        "jokey",
        "sarcastic",
        "sad",
        "happy"
    ]
    
    static var dialogue = [
        "I see what you are referring to.",
        "That appears to be the case.",
        "I can do that if needed.",
        "It should be finished later.",
        "I will check on it.",
        "That is acceptable to me.",
        "We can discuss it tomorrow.",
        "I am not sure about that.",
        "The information was sent earlier.",
        "This may take some time.",
        "I will let you know.",
        "That seems reasonable.",
        "I have already looked into it.",
        "It does not affect the outcome.",
        "We should wait for confirmation.",
        "I can make the adjustment.",
        "That was mentioned previously.",
        "There is nothing else to add.",
        "The meeting starts at noon.",
        "I understand the request.",
        "It was completed as planned.",
        "We can move forward now.",
        "That depends on the schedule.",
        "I will follow up later.",
        "The results are consistent.",
        "It does not change anything.",
        "I will review the document.",
        "That option is available.",
        "We can proceed when ready.",
        "I do not have further questions.",
        "The system is functioning.",
        "That was not included.",
        "I will handle it.",
        "The task remains incomplete.",
        "We should consider the details.",
        "It aligns with the plan.",
        "I noticed the update.",
        "There are no objections.",
        "It can be arranged.",
        "The file was received.",
        "I will be present.",
        "That is all for now.",
        "The issue has been resolved.",
        "We can revisit this later.",
        "I agree with that.",
        "The deadline is unchanged.",
        "I do not see a problem.",
        "Everything is in order.",
        "That concludes the discussion.",
        "We will continue as scheduled.",
        "The ship will arrive soon.",
        "The spell has been prepared.",
        "We are still linked.",
        "The signal is stable.",
        "The portal remains open.",
        "I recognize your presence.",
        "The prophecy mentions this.",
        "Our paths have crossed again.",
        "The android is functioning.",
        "The castle gates are closed.",
        "I will stay with you.",
        "The stars are aligned.",
        "The blade has been recovered.",
        "The transmission was received.",
        "This bond still exists.",
        "The realm is secure.",
        "I was sent to find you.",
        "The experiment continues.",
        "Magic is still active here.",
        "We are not alone.",
        "The vow remains unbroken.",
        "The coordinates are correct.",
        "I trust you.",
        "The night is quiet.",
        "This is where we part."

    ]
    
    static var writingPrompts = [
      "Write about a character who wakes up with no reflection.",
      "Describe a city where everyone forgets everything at midnight.",
      "Write a story from the perspective of a tree in a busy park.",
      "A letter arrives 10 years late — and changes everything.",
      "Your main character can hear lies — but only from animals.",
      "The sun doesn't rise one morning. No one knows why.",
      "Write a breakup letter between a writer and their muse.",
      "A librarian discovers a book that predicts the future.",
      "Describe the last 60 seconds before a secret is revealed.",
      "Your character can pause time, but only for 3 minutes per day.",
      "Write about a world where people trade dreams as currency.",
      "Your character’s shadow starts acting independently.",
      "An AI gains sentience and immediately wants to write poetry.",
      "A ghost is haunting your character — to help them finish their novel.",
      "Write a dialogue between two exes trapped in an elevator.",
      "A magician's last trick accidentally opens a portal.",
      "Describe a ritual performed once every hundred years.",
      "Your character wakes up in someone else’s memory.",
      "An artist discovers their paintings come true.",
      "Every decision today is being controlled by a coin flip.",
      "Write a scene where no one can lie — even by omission.",
      "A ship is lost at sea, but the ocean speaks to one passenger.",
      "Write a fairytale set in a cyberpunk dystopia.",
      "Describe a meal that saves someone’s life.",
      "Two strangers discover they share the same recurring dream.",
      "A haunted house demands a story in exchange for safe passage.",
      "Your protagonist finds a notebook labeled ‘DO NOT WRITE HERE.’",
      "A planet where the seasons change every day.",
      "Write about the invention of an emotion.",
      "A love story that starts with a mistaken identity at a funeral.",
      "Your character wakes up in a world run by children.",
      "Every mirror shows a different version of the person looking in.",
      "Write about someone who remembers every version of reality.",
      "A dragon’s hoard contains only books.",
      "A town where people age backward.",
      "A love letter accidentally mailed to the wrong person.",
      "Describe a character who’s allergic to the future.",
      "Write a scene using only dialogue.",
      "A detective solves crimes by dreaming about them.",
      "A wedding is interrupted by a character from a forgotten story.",
      "Your character inherits a lighthouse and a cryptic diary.",
      "Write about a forgotten god returning for one last favor.",
      "Your character finds a map tattooed on their skin.",
      "Describe the end of a world — and the beginning of another.",
      "A spell goes wrong and swaps two characters’ writing styles.",
      "Write a monologue from a villain just before they change sides.",
      "A time traveler gets stuck in their least favorite era.",
      "Two rival authors are forced to co-write a bestseller.",
      "A character is cursed to speak only in song lyrics.",
      "Describe an underground library known only to a few.",
      "Your character discovers their imaginary friend is real — and angry.",
      "Write a scene where two characters argue using only metaphors.",
      "A world where dreams are taxed.",
      "Someone receives postcards from a place that doesn’t exist.",
      "A pandemic that only affects emotions.",
      "A bookstore that appears only at midnight.",
      "Your protagonist learns their story was written by someone else.",
      "A spaceship powered by stories.",
      "A machine that records your final thoughts before death.",
      "A child finds a key that unlocks a voice in their head.",
      "Write a scene involving a secret kept for generations.",
      "A message is found hidden in a famous painting.",
      "Your main character starts forgetting nouns — then names — then themselves.",
      "Describe a conversation between a human and a machine about art.",
      "Write a story that starts with a confession.",
      "A mirror that shows who you could have been.",
      "Two lovers communicate only through graffiti in the city.",
      "A stranger offers to erase one memory — but only one.",
      "A world where written words can be weaponized.",
      "Write about the moment the moon falls from the sky.",
      "A reality show where the prize is rewriting your past.",
      "Your character receives a letter from their future self — warning them.",
      "An archaeologist finds proof of a civilization that never existed.",
      "A new color is discovered, and it drives people mad.",
      "A town where everyone has the same recurring dream — until one night.",
      "Write from the POV of a character lost in a photograph.",
      "Your character discovers a hidden room in their house — with someone in it.",
      "Describe a society where people choose their own names at age 30.",
      "A fortune teller delivers a prophecy that was meant for someone else.",
      "A door appears in your character’s living room. No one else sees it.",
      "Write a comedy set during the apocalypse.",
      "A pen that writes only the truth — no matter what.",
      "Your character is interviewed by a historian from the future.",
      "Describe a party where time moves differently in each room.",
      "A character falls in love with someone from a different timeline.",
      "A world where birthdays determine your fate — literally.",
      "A creature who lives in unfinished stories.",
      "A museum that collects regrets.",
      "Write about someone who steals people’s voices — and sells them.",
      "Your protagonist must teach a class of mythical creatures.",
      "A train that stops only for people with broken hearts.",
      "Your character hears a song no one else can — and it’s getting louder.",
      "A courtroom where characters from different genres are on trial.",
      "Write about a holiday that doesn’t exist — but should.",
      "Describe a character whose lies become reality.",
      "An annual event where people relive one moment of their life.",
      "A library that lets you borrow moments from others’ lives.",
      "Your protagonist must write a story — or vanish.",
      "Write a horror story without using any supernatural elements.",
      "A spaceship crash-lands on Earth — with a familiar face aboard.",
      "A child who remembers their past five lives.",
      "Two people share a soul — and have never met.",
      "A famous author disappears mid-book — and you’re chosen to finish it.",
      "Describe a scene where the world ends quietly.",
      "A machine that prints your destiny, but it’s jammed.",
      "Your character learns they are the villain in someone else’s story.",
      "Write about a secret society of writers who shape reality.",
      "A child writes a story that starts coming true.",
      "A library where books are alive — and arguing.",
      "The stars in the sky begin to rearrange themselves. One message at a time."
    ];

    static var vocabMap = [
        "abrogate": "to revoke or abolish formally",
        "anachronism": "something out of its proper time",
        "arrant": "complete and utter",
        "artless": "without cunning or deceit",
        "asperity": "harshness of manner or tone",
        "avarice": "insatiable greed for riches",
        "belligerent": "hostile and aggressive",
        "bombastic": "high‑sound but with little meaning; inflated",
        "bucolic": "relating to pleasant countryside or rural life",
        "byzantine": "excessively complex or intricate",
        "cajole": "persuade by flattery or coaxing",
        "candour": "frankness or honesty",
        "castigate": "to criticize or punish severely",
        "circumlocution": "the use of many words where fewer would do",
        "conflagration": "a large and destructive fire",
        "connive": "to secretly allow or conspire",
        "contumacious": "stubbornly disobedient",
        "corroborate": "confirm or give support to",
        "craven": "very cowardly",
        "debacle": "a sudden disastrous failure",
        "debauchery": "excessive indulgence in sensual pleasures",
        "decadent": "characterized by decay or decline in morals",
        "deleterious": "harmful or damaging",
        "demagogue": "a leader who appeals to emotions rather than reason",
        "denouement": "the outcome of a complex sequence of events",
        "desultory": "lacking a plan or purpose; random",
        "diaphanous": "very sheer and light; almost transparent",
        "diffident": "modest or shy because of lack of self‑confidence",
        "disparate": "fundamentally different or distinct",
        "ebullient": "overflowing with enthusiasm or excitement",
        "eclectic": "deriving ideas or style from a broad range of sources",
        "effervescent": "vivacious and enthusiastic",
        "egregious": "outstandingly bad or shocking",
        "elucidate": "make (something) clear; explain",
        "emulate": "to imitate with the aim of matching or surpassing",
        "enervate": "to weaken or drain of energy",
        "enigmatic": "difficult to interpret or understand; mysterious",
        "ephemeral": "lasting for a very short time",
        "equivocate": "to speak ambiguously or evasively",
        "erudite": "having or showing great knowledge",
        "esoteric": "intended for or likely to be understood by only a few",
        "evanescent": "soon passing out of sight, memory or existence",
        "exacerbate": "to make worse or more severe",
        "exculpate": "to free from blame or guilt",
        "exigent": "urgent, pressing",
        "explicate": "to explain in detail",
        "fastidious": "very attentive to and concerned about accuracy and detail",
        "feckless": "lacking initiative or strength of character; irresponsible",
        "furtive": "attempting to avoid notice or attention; secretive",
        "garrulous": "excessively talkative",
        "grandiloquent": "using lofty or pompous speech",
        "gregarious": "fond of company; sociable",
        "harangue": "a lengthy and aggressive speech",
        "hegemony": "leadership or dominance by one group over others",
        "iconoclast": "one who attacks cherished beliefs or institutions",
        "ignominious": "deserving or causing public disgrace or shame",
        "impecunious": "having little or no money",
        "imperious": "assuming power or authority without justification; arrogant",
        "implacable": "unable to be placated or appeased",
        "inchoate": "just begun and so not fully formed or developed",
        "incorrigible": "not able to be corrected or improved",
        "indefatigable": "persisting tirelessly",
        "indolent": "lazy or avoiding activity",
        "ineffable": "too great or extreme to be expressed in words",
        "inexorable": "impossible to stop or prevent",
        "insidious": "proceeding in a gradual, subtle way but with harmful effects",
        "intrepid": "fearless and adventurous",
        "intransigent": "unwilling to change one’s views or to agree",
        "inveterate": "having a habit long established; deep‑rooted",
        "juxtapose": "to place side by side for contrast",
        "laconic": "using very few words; concise",
        "largesse": "generosity in giving; lavish gift",
        "laudable": "worthy of praise",
        "lethargic": "lacking energy; sluggish",
        "lugubrious": "look­ing or sounding sad and dismal",
        "malaise": "a general feeling of discomfort or unease",
        "malfeasance": "wrongful conduct by a public official",
        "maverick": "an independent thinker or dissenter",
        "meticulous": "extremely careful and precise",
        "milieu": "the physical or social setting in which something occurs",
        "misanthrope": "a person who dislikes humankind",
        "neophyte": "a beginner or novice",
        "nexus": "a connection or series of connections",
        "obdurate": "stubbornly refusing to change",
        "obfuscate": "to render obscure or unclear",
        "obsequious": "excessively obedient or attentive",
        "obtuse": "slow to understand; dull",
        "odious": "extremely unpleasant; repulsive",
        "onerous": "involving a great deal of effort and difficulty",
        "opulent": "rich, luxurious, wealthy",
        "ostensible": "stated or appearing to be true, but not necessarily so",
        "ostentatious": "characterized by vulgar or pretentious display",
        "panacea": "a solution or remedy for all problems",
        "paradigm": "a typical example or model",
        "paragon": "a model of excellence",
        "parsimonious": "unwilling to spend money or use resources",
        "penchant": "a strong or habitual liking for something",
        "perfidy": "the state of being deceitful or untrustworthy",
        "perfunctory": "carried out with minimal effort or reflection",
        "perspicacious": "having keen understanding or insight",
        "petrichor": "the smell of earth after rain",
        "plethora": "a large or excessive amount",
        "platitude": "a remark that is overused and lacks originality",
        "plebeian": "common, of the lower class",
        "polemical": "relating to or involving strongly critical debate",
        "precarious": "not securely held or in position; dangerously unstable",
        "precocious": "having abilities earlier than normal",
        "prevaricate": "to speak or act in an evasive way",
        "proclivity": "a tendency to choose or do something regularly",
        "prosaic": "commonplace; lacking poetic beauty",
        "pugnacious": "eager or quick to argue or fight",
        "punctilious": "showing great attention to detail or correct behaviour",
        "quixotic": "exceedingly idealistic; unrealistic",
        "rancorous": "characterized by bitterness or resentment",
        "recalcitrant": "having an obstinately uncooperative attitude",
        "recondite": "little known; abstruse",
        "reprobate": "an unprincipled person",
        "rescind": "to revoke, cancel, or repeal",
        "sagacious": "having keen mental discernment; wise",
        "sanctimonious": "making a show of being morally superior",
        "sanguine": "optimistic or positive, especially in bad situation",
        "scintillating": "brilliantly lively, stimulating",
        "soporific": "tending to induce drowsiness or sleep",
        "spurious": "not genuine; false or fake",
        "stipulate": "to require as an essential condition",
        "strident": "loud and harsh; grating",
        "stupendous": "extremely impressive",
        "subjugate": "to bring under domination or control",
        "sublime": "of great excellence or beauty",
        "surreptitious": "kept secret, especially because it would not be approved",
        "sycophant": "a person who acts obsequiously toward someone important in order to gain advantage",
        "temerity": "excessive confidence or boldness; audacity",
        "tenacious": "tending to keep a firm hold; persistent",
        "tranquil": "free from disturbance; calm",
        "trepidation": "a feeling of fear or agitation about something that may happen",
        "truculent": "eager to argue or fight; aggressively defiant",
        "turbulent": "characterised by conflict, disorder or confusion; violent or unsteady",
        "ubiquitous": "present, appearing or found everywhere",
        "unctuous": "excessively flattering or oily in manner",
        "usurp": "to take a position of power or importance illegally or by force",
        "vainglorious": "excessively proud of oneself or one’s achievements; overly vain",
        "venerate": "to regard with great respect",
        "veracity": "conformity to facts; truthfulness",
        "verbose": "using more words than necessary; wordy",
        "vicissitude": "a change of circumstances or fortune, typically one that is unwelcome or unpleasant",
        "vindicate": "to clear from accusation or suspicion",
        "vitriolic": "filled with bitter criticism or malice",
        "vociferous": "voicing or crying out noisily; clamorous",
        "voluble": "speaking or spoken incessantly and fluently",
        "wane": "to decrease in size or extent",
        "zealous": "having or showing great energy or enthusiasm",
        "zenith": "the highest point; peak"
      ]
    
    static var badSentences = [
      "He walked very quickly fast to the store because he needed to get some stuffs that he forgot it.",
      "The dog barked, barked and kept barking loud until the man he was there came back to the place.",
      "She was like, you know, kind of going to maybe do the thing later if she had the time, I guess.",
      "It was a dark night and also stormy too with lots of raining and the lightning was also very loud.",
      "They goes to the beach but it was too sandy and hot so they leaved early and fastly.",
      "John he was a man who liked books that were in the library and he read them a lot many times.",
      "Suddenly out of nowhere the loud noise loudly scared everyone who were already scared before.",
      "The cat sat on the mat and then it sit there again but different this time because it was bored.",
      "I think that maybe possibly he might have been trying to attempt to sort of ask her out maybe.",
      "She runned fastly down the stairs while falling and also she had a phone call at the same exact moment.",
      "The sun was shining so bright it blinded my eyes even though I had sunglasses on my eyes on.",
      "He was the type of person who always used to be the type who talks too much of talking.",
      "They didn't never go to the park no more because of the bees that stung them previously before.",
      "Her eyes was blue like the ocean but not really like that because oceans are green too sometimes.",
      "There is a dog that was outside and it barked and then barked and then barked some more again.",
      "He had did the thing that nobody else didn't ever do before in the past of before.",
      "Walking down the hallway the door suddenly opened which startled me unexpected very much.",
      "The sandwich was tasting like old socks and I know because I maybe probably ate one once.",
      "The room was full of furniture that was furnishing the room full of stuff and chairs and things.",
      "She had a hair that looked like gold and it was long and brown and kind of golden also.",
      "He talks like as if he knows everything even though he doesn’t really know anything actually.",
      "There’s a loud sound that makes a noise and it's sounding loud and noisy in the loud room.",
      "The man, who was old and aged, he looked tired and sleepy and also like he needed a nap.",
      "I seen him yesterday at the mall when he was shopping for shopping things in the shop store.",
      "My phone, it fell down on the ground floor and broke into pieces that was shattered broken.",
      "It was raining rain that was wet and the water fell down like water does from the sky above.",
      "I can’t hardly never find nothing that I want to find when I am looking for it somewhere.",
      "He did a thing that was something that people don't usually do on normal kind of days.",
      "The cake tasted sweetly sugary with sugar sweetness like sugar does when it's sweet tasting.",
      "After they runned the race, they were tired from the running of the racing they did.",
      "The bird flied high up in the sky so high it was like really high above everything else.",
      "She had a voice that sounded like music but more like noise that was musical sounding kinda.",
      "He went inside the room that was inside the house that had a door that opened open.",
      "I don’t want to go to no place where nobody don’t never do nothing fun at all ever.",
      "The stars was shining in the sky above in the nighttime where stars shine bright often.",
      "He looked at her with eyes that were looking like eyes do when they look at someone.",
      "There were lots of people and they all was talking and saying things and speaking words.",
      "Her dress was red like a tomato but also pinkish and kind of orangey depending on light.",
      "The wind blowed hard and fast with blowingness and it made the leaves blow around a lot.",
      "I had went to the restaurant where I eated food that was food they serve at places like that.",
      "They were playing the game of the sport kind and were losing the win because of points.",
      "Time went slow as molasses in January on a cold day when time is slow and cold.",
      "He was standing there, just standing, in a standing way that people stand when they stand.",
      "The computer wasn't turning on so I turned it off again but it was already off though.",
      "She kept saying the same things over and over again repeatedly like a repeating machine.",
      "In the backyard behind the house there was a tree that grew upward into the up sky.",
      "He smiled a smile that showed teeth and happiness and facial expressions of joy and smiling.",
      "The movie was so boring I almost died of boredom from being bored of it during watching.",
      "She had a look that looked like she was looking at something that was looking weirdly."
    ]

}
